app/__init__.py
__author__ = 'sharads'

from flask import Flask

app = Flask(__name__)
app.config['DEBUG'] = True

# import and register Blueprint
from app.routes.home import home
from app.routes.blog import blog
app.register_blueprint(home)
app.register_blueprint(blog)


app/routes/__init__.py
__author__ = 'sharads'

app/routes/blog.py
__author__ = 'sharads'

from flask import Blueprint, render_template

blog = Blueprint('blog', __name__, url_prefix='/blog')


@blog.route('/')
def blog_page():
    """the blog page"""
    return render_template('blog.html')

app/routes/home.py
__author__ = 'sharads'

from flask import Blueprint, render_template


home = Blueprint('name', __name__)


@home.route('/')
def home_page():
    """
    the home page
    """
    return render_template('home.html')


app/templates/blog.html
{% extends "home.html" %}
{% block title %}Blog | {{ super }}{% endblock %}
{% block current_page %}Blog{% endblock %}

{% block content %}
<h2>Check out my posts!</h2>
{% endblock %}

app/templates/home.html
<html>
<head>
  <title>{% block title %}Blask!{% endblock %}</title>
  <link rel='stylesheet' 
      type='text/css'
      href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400'>
  <link rel="stylesheet" 
      type="text/css" 
      href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
  <nav>
    <div class="content">
      <h1><a href="/">Blask!</a></h1>
      <h2>{% block current_page %}Home{% endblock %}</h2>
      <ul class="menu">
        <li>
          <a href="{{ url_for('home.home_page') }}">Home</a>
        </li>
        <li>
          <a href="{{ url_for('blog.blog_page') }}">Blog</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="content">
    {% block content %}
    <h2>Welcome to Blask!</h2>
    {% endblock %}
  </div>

  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

app/templates/something.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h2> something </h2>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}Blask!{% endblock %}</title>
    <link rel = 'stylesheet'
          type = 'text/css'
          href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400'>
    <link rel = 'stylesheet'
          type = 'text/css'
          href = "{{ url_for('static', filename='css/style.css') }}">
</head>
<body>

</body>
</html>